#pragma once

#include <juce_core/juce_core.h>
#include <juce_audio_processors/juce_audio_processors.h>

namespace glos::clcr
{

/**
 * @brief Gaussian white noise generator using the Box-Muller transform.
 * 
 */
class BoxMullerNoise
{
public:

    /**
     * @brief Construct a new Box Muller Noise object
     * 
     */
    BoxMullerNoise() = default;

    /**
     * @brief Construct a new Box Muller Noise object
     * 
     * @param numChannels Number of channels to generate noise for
     * @param sampleRate Host sample rate
     */
    BoxMullerNoise(int numChannels, int sampleRate);

    /**
     * @brief Compute a gaussian noise sample using the Box-Muller transform.  This implementation
     * uses the Marsaglia polar method instead of the standard trigonometric version of the Box-Muller
     * transform, which is more efficient and avoids the need for executing trigonometric functions in the audio
     * processing loop.
     * 
     * @return float 
     */
    float nextSample() noexcept;

    /**
     * @brief Compute a fixed number of gaussian noise samples.
     * 
     * @param n Number of samples to generate
     * @return std::AudioBuffer<float>
     */
    juce::AudioBuffer<float> nextNSamples(int n) noexcept;

private:
    bool m_usePrecomputedSample = false; /**< Boolean flag used for determining if a precomupted sample can be used */
    float m_precomputedSample = 0.0f; /**< Value that stores one of the two value generated by the Box-Muller method  */

    juce::Random m_random = juce::Random(); /**< Uniformly distributed random number generator */
    juce::AudioBuffer<float> m_samples = juce::AudioBuffer<float>(1, 44100); /**< AudioBuffer to store multiple samples if needed */
};

}